import turtle
def drawsquare():
    window=turtle.Screen()
    window.bgcolor("red")
    brad=turtle.Turtle()
    brad.shape("circle")
    brad.color("yellow")
    brad.speed(2)
    brad.forward(50)
    brad.right(90)
    brad.forward(50)
    brad.right(90)
    brad.forward(50)
    brad.right(90)
    brad.forward(50)
    brad.right(90)
    ang=turtle.Turtle()
    ang.shape("arrow")
    ang.color("blue")
    ang.circle(50)
    window.exitonclick()
drawsquare()
